blueprint:
  name: Niko Cover Sync
  description: Sync a virtual cover in Niko Home Control with an actual cover device (e.g., Somfy, Velux)
  domain: automation
  author: thiesens
  source_url: https://github.com/thiesens/homeassistant-blueprints/blob/main/blueprints/automation/niko_cover_sync.yaml
  input:
    actual_cover:
      name: Actual Cover Device
      description: The physical cover device (e.g., Somfy, Velux window/blind)
      selector:
        entity:
          domain: cover
          multiple: false
    virtual_cover:
      name: Virtual Niko Cover
      description: The virtual cover device in Niko Home Control
      selector:
        entity:
          domain: cover
          multiple: false
    sync_delay:
      name: Sync Delay
      description: Delay in seconds after a state change before syncing to prevent rapid re-triggering
      default: 1.5
      selector:
        number:
          min: 0.5
          max: 5
          step: 0.5
          unit_of_measurement: seconds

trigger:
  - platform: state
    entity_id: !input actual_cover
    attribute: current_position
  - platform: state
    entity_id: !input actual_cover
    attribute: current_tilt_position
  - platform: state
    entity_id: !input virtual_cover
    attribute: current_position
  - platform: state
    entity_id: !input virtual_cover
    attribute: current_tilt_position

condition: []

action:
  # Add delay to allow state to settle and prevent rapid re-triggering
  - delay:
      seconds: !input sync_delay

  - choose:
      # Sync actual to virtual
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (actual_cover | string) }}"
        sequence:
          - service: cover.set_cover_position
            target:
              entity_id: !input virtual_cover
            data:
              position: "{{ state_attr(actual_cover, 'current_position') | int(0) }}"
          # Sync tilt position if available
          - if:
              - condition: template
                value_template: "{{ state_attr(actual_cover, 'current_tilt_position') is not none }}"
            then:
              - service: cover.set_cover_tilt_position
                target:
                  entity_id: !input virtual_cover
                data:
                  tilt_position: "{{ state_attr(actual_cover, 'current_tilt_position') | int(0) }}"

      # Sync virtual to actual
      - conditions:
          - condition: template
            value_template: "{{ trigger.entity_id == (virtual_cover | string) }}"
        sequence:
          - service: cover.set_cover_position
            target:
              entity_id: !input actual_cover
            data:
              position: "{{ state_attr(virtual_cover, 'current_position') | int(0) }}"
          # Sync tilt position if available
          - if:
              - condition: template
                value_template: "{{ state_attr(virtual_cover, 'current_tilt_position') is not none }}"
            then:
              - service: cover.set_cover_tilt_position
                target:
                  entity_id: !input actual_cover
                data:
                  tilt_position: "{{ state_attr(virtual_cover, 'current_tilt_position') | int(0) }}"

mode: parallel
max_exceeded: silent
